version: '2'
services:
    remote:
        build:
            context: ./remote
            dockerfile: Dockerfile
        image: hackssh-remote
        container_name: remote
        tty: true
        stdin_open: true
    local:
        build:
            context: ./local
            dockerfile: Dockerfile
        image: hackssh-local
        container_name: local
        tty: true
        stdin_open: true
        links:
            - remote
